### ISSUE TITLE
missing line in basic_gp_example.py

### ISSUE THREAD

**Issue by bwheelz36** [adkoo/Bayesian-optimization-using-Gaussian-Process#3]
You need to add this in:
optimize_kernel_on_the_fly = 2 # or None

Also - what does the number here mean? does it have to be 2 or can it be other numbers?

**Comment by bwheelz36** [comment]
and hyperparams need to be
hyperparams = {'precisionMatrix': gp_precisionmat, 'amplitude_covar': gp_amp, 'noise_variance': gp_noise_variance}
(I took both from the notebook example)

**Comment by adkoo** [comment]
Hi, I pushed the change. Thanks!

optimize_kernel_on_the_fly is the iteration number to start optimize the kernel's hyperparmaters. If None, no optimization of the hypers during BO.

**Comment by bwheelz36** [comment]
Still missing this:
hyperparams = {'precisionMatrix': gp_precisionmat, 'amplitude_covar': gp_amp, 'noise_variance': gp_noise_variance}

the mplitude_covar field is missing in the py example
